default: &default
  logger:
    path: 'log/solr.log'
    age: 5
    size: 5242880
  connection:
    open_timeout: 20
    read_timeout: 20
    time_out_sec: 600
    retry_503: 2

development:
  <<: *default
  object_core:
    url: http://localhost:8983/solr/gettingstarted
  master_object_core:
    url: http://localhost:8983/solr/gettingstarted
    data_import_handler: dataimport


# development:
#   solr:
#     hostname: localhost
#     port: 8983
#     log_level: INFO
#     path: /solr/gettingstarted
#     solr_home: solr
